### ISSUE TITLE
Fix Mac M1 here :)

### ISSUE THREAD

**Issue by llermaly** [tomasonjo/neo4j-hp-viz#1]
Hello, first THANKS this project. I wasted many hours trying to figure out how to do this.

Second I have a Macbook pro M1 and I had troubles running the neo4j docker image.

FIX: 

`docker pull neo4j/neo4j-arm64-experimental:4.2.11-arm6`

Then replace in docker-compose.yml

```
eo4j:
    image: neo4j/neo4j-arm64-experimental:4.2.11-arm64
```

Thanks again

**Comment by llermaly** [comment]
do you want a PR for this to take place in the documentation? @tomasonjo

**Comment by tomasonjo** [comment]
Sure, you can update the docs. Thanks
